# This file configures the analyzer to use best practices for Flutter apps.
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Avoid relative imports for files in lib/
    - always_use_package_imports
    # Use const constructors where possible
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    # Formatting
    - prefer_single_quotes
    - sort_child_properties_last
    - use_colored_box
    - use_decorated_box
    # Style
    - avoid_print
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_lambdas
    - unnecessary_parenthesis
    # Documentation
    - public_member_api_docs: false
